blogapp/urls.py
from django.conf.urls import include, url
from . import views
from django.views.generic.dates import ArchiveIndexView
from blogapp.views import ArticleMonthArchiveView
from .models import Post

urlpatterns = [
    url(r'^$', views.index),
    url(r'^about$', views.about),
    url(r'^blog$', views.post_list),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^archive/$',
        ArchiveIndexView.as_view(model=Post, date_field="published_date"),
        name="post_archive"),
    # Example: /2012/aug/
    url(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/$',
        ArticleMonthArchiveView.as_view(),
        name="archive_month"),
    # Example: /2012/08/
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        ArticleMonthArchiveView.as_view(month_format='%m'),
        name="archive_month_numeric"),
]

qblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sentosaapp import views as sentosaappview

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blogapp.urls')),
    url(r'^sentosaapp/', include('sentosaapp.urls')),
    url(r'^markdown/', include('django_bootstrap_markdown.urls')),
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}, name="my_login"),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'sentosaapp/login.html'}, name="my_login"),
]


handler404 = sentosaappview.error404

blogapp/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager

# https://github.com/alex/django-taggit
class Post(models.Model):

    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=400)
    text = models.TextField()

    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    tags = TaggableManager()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __unicode__(self):
        return self.title

blogapp/forms.py
from django import forms
from .models import Post
from bootstrap_markdown.widgets import MarkdownEditor

class PostForm(forms.ModelForm):
    #text = forms.CharField(widget=MarkdownEditor())

    class Meta:
        model = Post
        widgets = {
          #'text': forms.Textarea(attrs={'rows':40, 'cols':50}),
          'text': MarkdownEditor(attrs={'id': 'title',
                                        'width': "80%",
                                        'height': 400,
                                        'locale': None,
                                        'boostrap_cdn': True,
                                        'autofocus': True,
                                        'resize': 'both',
                                        'icon': 'glyph',
                                        'footer': '> Powered by http://www.codingdrama.com/bootstrap-markdown',
                                        'fullscreen': True,
                                    }),
          'title': forms.TextInput(attrs={'size': 80, 'title': 'Title',})
        }
        fields = ('title', 'text',)

blogapp/views.py
from django.shortcuts import render,render_to_response
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.dates import MonthArchiveView
from .models import Post
from .forms import PostForm

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

BLOGPERPAGE=5

class ArticleMonthArchiveView(MonthArchiveView):
    queryset = Post.objects.all()
    date_field = "published_date"
    allow_future = True

def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
    return render(request, 'blogapp/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blogapp.views.post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blogapp.views.post_list')

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    paginator = Paginator(posts, BLOGPERPAGE)
    page = request.GET.get('page')

    try:
        ps = paginator.page(page)
    except PageNotAnInteger: # If page is not an integer, deliver first page.
        ps = paginator.page(1)
    except EmptyPage: # If page is out of range (e.g. 9999), deliver last page of results.
        ps = paginator.page(paginator.num_pages)
    '''
    <nav>
    <ul class="pagination pagination-sm">
    <li class="disabled">
      <span>
        <span aria-hidden="true">&laquo;</span>
      </span>
    </li>
    <li class="active">
      <span> 1 </span>
    </li>
    <li class="disabled">
      <span>
        <span aria-hidden="true"> &raquo; </span>
      </span>
    </li>
    </ul>
    </nav>
    '''
    nav='<nav>'
    if ps.has_previous():
        nav=nav+"[< previous](?page={}) | ".format(ps.previous_page_number())
    nav = nav + "Page {} of {}".format(ps.number,ps.paginator.num_pages)
    if ps.has_next():
        nav=nav+" | [next >](?page={})".format(ps.next_page_number())
    nav=nav+'</nav>'

    return render(request, 'blogapp/index.html', {'ps': ps,'nav': nav})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blogapp/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blogapp.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blogapp/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    #print "pk: ",pk
    post = get_object_or_404(Post, pk=pk)
    #print "post: ",post
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blogapp.views.post_detail', pk=post.pk)
        else:
            print "form is invalid:", form
    else:
        form = PostForm(instance=post)
    return render(request, 'blogapp/post_edit.html', {'form': form})
    #return render_to_response('blogapp/edit.html', {'form': form, 'post':post})

from django.http import HttpResponseRedirect
def index(request):
    #return render(request, 'index.html')
    return HttpResponseRedirect("/post/48/")

def about(request):
    return HttpResponseRedirect("/post/58/")

templates/blogapp/base.html
<!-- start of base template -->

{% include 'header.html' %}

<link rel="stylesheet" href="http://{{domain}}/static/v/0.2/strapdown.css">
<div class="row" id="FuhengMarkDown">
    <xmp theme="Cerulean" style="display:block;">
    {% block content %}
    {% endblock %}
    </xmp>
</div>
<script src="/static/v/0.2/strapdown.js"></script>

{% include 'footer.html' %}

<!-- end of base template -->

templates/blogapp/base2.html
<!DOCTYPE html>
<html>
<head>
<title>WuFuheng's Blog - A pure markdown blog</title>
<meta charset="UTF-8">
<script type="text/x-mathjax-config"> MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}}); </script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<!--script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script-->

<style>
  .container {
    width:60% !important;
    padding: 20px 20px 20px 20px;
  }
</style>
</head>

<xmp theme="Cerulean" style="display:none;"></xmp>
{% block content %}
{% endblock %}
<hr>
<center>Copyright @ 2015</center>

<script src="http://strapdownjs.com/v/0.2/strapdown.js"></script>
</html>

templates/blogapp/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap Markdown Editor</title>

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css" rel="stylesheet">
        <link href="http://inacho.github.io/bootstrap-markdown-editor/dist/css/bootstrap-markdown-editor.css" rel="stylesheet">

    </head>

    <body>
        <div class="container">
            <form method="POST" class="post-form" id="form">{{ csrf_token }}
            <p><label for="id_title">Title:</label> <input id="id_title" maxlength="200" name="title" type="text" value="{{ post.title }}" /></p>
                <div id="editor">
                {{ post.text }}
                </div>
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>

        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/marked/0.3.2/marked.min.js"></script>
        <script src="http://inacho.github.io/bootstrap-markdown-editor/dist/js/bootstrap-markdown-editor.js"></script>

        <script>
            jQuery(document).ready(function($) {
                $('#editor').markdownEditor({
                    preview: true,
                    onPreview: function (content, callback) {
                        callback( marked(content) );
                    }
                });
            });
        </script>
    </body>
</html>

templates/blogapp/index.html
<!-- start of index template -->

{% extends 'blogapp/base.html' %}

{% block content %}
{{nav|safe}}

----

<!-- start of a for loop, loop in the posts -->
{% for post in ps %}
#### ![](/static/img/blog.png "{{ post.title }}")[{{ post.title }}]({{ url('blogapp.views.post_detail',args=[post.pk]) }}) <small class='text-right'> Published at: {{ post.published_date }} {% if request.user.is_authenticated() %} | <a href="{{url('post_edit',args=[post.pk])}}">edit</a> {%endif%} </small>

{{ post.text|safe }}

----
{% endfor %}
<!-- end of a for loop, loop in the posts -->

{% endblock content %}

<!-- end of index template -->

templates/blogapp/post_archive.html
{% extends 'blogapp/base.html' %}
{% block content %}
----

{% for post in latest %}
- [{{ post.title }}]({{ url('blogapp.views.post_detail',args=[post.pk]) }}) <small>{{post.published_date}}</small>
{% endfor %}


{% endblock content %}

templates/blogapp/post_archive_month.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<ul>
    {% for article in object_list %}
        <li>{{ article.published_date }}: {{ article.title }}</li>
    {% endfor %}
</ul>

<p>
    {% if previous_month %}
        Previous Month: {{ previous_month }}
    {% endif %}
    {% if next_month %}
        Next Month: {{ next_month }}
    {% endif %}
</p>
</body>
</html>

templates/blogapp/post_detail.html
{% extends 'blogapp/base.html' %}

{% block content %}
----

{% if request.user.is_authenticated() %}
{% if post.published_date %}
{{ post.published_date }}
{% else %}<a class="btn btn-primary btn-sm" href="{{ url('blogapp.views.post_publish',args=[post.pk]) }}">Publish</a>{% endif %}
<a class="btn btn-success btn-sm" href="{{url('post_edit',args=[post.pk])}}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
<a class="btn btn-danger btn-sm" href="{{url('post_remove',args=[post.pk])}}"><span class="glyphicon glyphicon-remove">Delete</span></a>
{% endif %}

####{{ post.title }}

----

{{ post.text|safe }}

----

{% endblock content %}

templates/blogapp/post_draft_list.html
{% extends 'blogapp/base.html' %}

{% block content %}
{% for post in posts %}
----


{% if request.user.is_authenticated() %}
{% if post.published_date %}
__ {{ post.published_date }} __
{% else %}<a class="btn btn-primary btn-sm" href="{{url('blogapp.views.post_publish',args=[post.pk])}}"><span class="glyphicon glyphicon-pencil">Publish</span></a>{% endif %}
<a class="btn btn-success btn-sm" href="{{url('post_edit',args=[post.pk])}}"><span class="glyphicon glyphicon-pencil">EDIT</span></a>
<a class="btn btn-danger btn-sm" href="{{url('post_remove',args=[post.pk])}}"><span class="glyphicon glyphicon-remove">DELE</span></a>
{% endif %}

#### ![](/static/img/blog.png "{{ post.title }}")[{{ post.title }}]({{ url('blogapp.views.post_detail',args=[post.pk]) }})

{{ post.text|safe }}

{% endfor %}
{% endblock %}

templates/blogapp/post_edit.html
{% include 'header.html' %}

<script type="text/javascript">
//<![CDATA[
        (function($) {
            $(document).ready(function() {
                $('input[type="submit"]').addClass('btn');
                $('[title]').tooltip();
            });
        }(jQuery));

//]]>
</script>


<div class=" dashboard">
<div class="row">
    <form method="POST" class="post-form"><input class="control-group" type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        {{ form.as_p() |safe }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>
</div>
<script>
    $("#id_title").attr('class','form-control');
</script>
{% include 'footer.html' %}
<!--script src="/static/v/0.2/strapdown.js"></script-->

templates/blogapp/post_edit2.html
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

templates/blogapp/post_list.html
{% extends 'blogapp/base.html' %}
{% block content %}
{% for post in posts %}
###[{{ post.title }}]({% url 'blogapp.views.post_detail' pk=post.pk %})
  Published: {{ post.published_date }}

{% autoescape off %}
{{ post.text }}
{% endautoescape %}
----
{% endfor %}
{% endblock content %}